### ISSUE TITLE
Add: Tab component

### ISSUE THREAD

**Issue by MuhannedNoman** [ReCoded-Org/capstone-turkey-react-student-teach#34]
Is your feature request related to a problem? Please describe.
N/A

Describe how the solution should behave
The tab component will display two components, the first will use the question component previously used on the home page and the other component should display the comment component of the same user.

Screenshots of the design/if any
![image](https://user-images.githubusercontent.com/40465727/164330644-b84c4d2c-615a-4b1f-a636-219ad437a108.png)

Additional context
N/A

**Comment by aliSalehAbdulhadi** [comment]
I already added this with issue #35
